### ISSUE TITLE
clean install with pgsql

### ISSUE THREAD

**Issue by ketheriel** [alanhogan/lessnmore#27]
Installing/Upgrading Lessn More

Running migration create_autoslug_table::up to version 5

    This migration enables an efficient method of generating automatic slugs.

    Failed: Failed to migrate, rolling back.
    exception 'PDOException' with message 'SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "id" violates not-null constraint
    DETAIL: Failing row contains (null, base36, 1).' in /var/www/lessnmore/-/migrations/005_create_autoslug_table.php:34
    Stack trace:
    #0 /var/www/lessnmore/-/migrations/005_create_autoslug_table.php(34): PDOStatement->execute()
    #1 /var/www/lessnmore/-/library/Migrator.php(91): Create_Autoslug_Table->up()
    #2 /var/www/lessnmore/install.php(20): Migrator->migrate(NULL)
    #3 {main}

You will probably want to delete install.php when finished installing/migrating.

**Comment by alanhogan** [comment]
@ketheriel The script expects the `null` to be turned into an automatically assigned primary key. What version of which database system are you using?

I expect you should be able to resolve this by either changing the `null`(s) to 1[, 2, 3…] or making a similar change.

I don’t do much active maintaining around here but please do report back so we can help others with a similar issue if it comes up again.
